# EDA -- Titanic dataset
*исходники --->* https://www.kaggle.com/competitions/titanic/data

сеттим библиотеки

In [64]:
import pandas as pd

## A) Быстрый обзор данных (Pandas)

In [65]:
df = pd.read_csv("TitanicDataset/train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [66]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [67]:
print( "table size --> ",df.shape)

table size -->  (891, 12)

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [69]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [70]:
df.describe(include="object")

C:\Users\Honor\AppData\Local\Temp\ipykernel_5668\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [71]:
print("пропуски : \n" , df.isnull().sum())

пропуски :
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [72]:
print("Количество дубликатов -->", df.duplicated().sum())

Количество дубликатов --> 0

## B) Пропуски и очистка

In [73]:
print("Средний возраст --> ", df['Age'].median())

Средний возраст -->  28.0

In [74]:
# сеттим средний возраст в пропущенные ячейки возраста
df['Age'] = df['Age'].fillna(df['Age'].median())

In [75]:
# сеттим моду в категориальную колонку Embarked с пропущенными значениями
print("Мода Embarked --> ", df['Embarked'].mode()[0])
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

Мода Embarked -->  S

In [ ]:
#удаляем колонку Cabin тк слишком много пропусков
df = df.drop('Cabin', axis=1)

In [79]:
# финальный чек 
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## C) Расширенная статистика

In [ ]:
numCols = ['Pclass','Age','SibSp','Parch','Fare']

for col in numCols :
    print(f"\n{col}")
    print("min value--> ", df[col].min())
    print("max value--> ", df[col].max())
    print("mean value --> ", df[col].mean())
    print("median value --> ",df[col].median())
    print("mode value --> ", df[col].mode()[0])

Pclass
min value-->  1
max value-->  3
mean value -->  2.308641975308642
median value -->  3.0
mode value -->  3

Age
min value-->  0.42
max value-->  80.0
mean value -->  29.36158249158249
median value -->  28.0
mode value -->  28.0

SibSp
min value-->  0
max value-->  8
mean value -->  0.5230078563411896
median value -->  0.0
mode value -->  0

Parch
min value-->  0
max value-->  6
mean value -->  0.38159371492704824
median value -->  0.0
mode value -->  0

Fare
min value-->  0.0
max value-->  512.3292
mean value -->  32.204207968574636
median value -->  14.4542
mode value -->  8.05

In [94]:
#перцентели
q_list = [0.05,0.25,0.5,0.75,0.95]

print(df[numCols].quantile(q_list))

      Pclass   Age  SibSp  Parch       Fare
0.05     1.0   6.0    0.0    0.0    7.22500
0.25     2.0  22.0    0.0    0.0    7.91040
0.50     3.0  28.0    0.0    0.0   14.45420
0.75     3.0  35.0    1.0    0.0   31.00000
0.95     3.0  54.0    3.0    2.0  112.07915